import mongoose, { Schema, Document } from 'mongoose';

export interface IBook extends Document {
  id: string;
  title: string;
  author: string;
  publisher: string;
  category: string;
  isbn?: string;
  accessionNo?: string;
  type?: string;
  fileFormat?: string;
  department?: string;
  semester?: string;
  subject?: string;
  year?: string | number;
  availableCopies?: number;
  isBookmarked?: boolean;
  coverImageUrl?: string;
  streamUrl?: string;
  fileUrl?: string;
  uploadedBy?: string;
  uploadedByUserId?: string;
  uploadedRole?: string;
  uploadedAt?: string;
  viewsCount?: number;
  downloadsCount?: number;
  allowDownload?: boolean;
  description?: string;
  fileSize?: string;
  fileName?: string;
  pageCount?: number;
  googleDriveFileId?: string;
  storageProvider: 'google-drive' | 'local';
  storageStatus: 'AVAILABLE' | 'MISSING' | 'UPLOAD_FAILED';
  isPublished: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

const BookSchema: Schema = new Schema(
  {
    id: { type: String, required: true, unique: true },
    title: { type: String, required: true },
    author: { type: String, required: true },
    publisher: { type: String, default: 'BHMC Academic Press' },
    category: { type: String, required: true },
    isbn: { type: String },
    accessionNo: { type: String },
    type: { type: String, default: 'BOOK' },
    fileFormat: { type: String, default: 'PDF' },
    department: { type: String, default: 'Organon of Medicine' },
    semester: { type: String, default: '1st BHMS' },
    subject: { type: String },
    year: { type: Schema.Types.Mixed, default: '2025-2026' },
    availableCopies: { type: Number, default: 10 },
    isBookmarked: { type: Boolean, default: false },
    coverImageUrl: { type: String },
    streamUrl: { type: String },
    fileUrl: { type: String },
    uploadedBy: { type: String, default: 'Librarian & Faculty Board' },
    uploadedByUserId: { type: String, default: 'usr-lib-001' },
    uploadedRole: { type: String, default: 'Librarian' },
    uploadedAt: { type: String },
    viewsCount: { type: Number, default: 0 },
    downloadsCount: { type: Number, default: 0 },
    allowDownload: { type: Boolean, default: true },
    description: { type: String },
    fileSize: { type: String },
    fileName: { type: String },
    pageCount: { type: Number, default: 1 },
    googleDriveFileId: { type: String },
    storageProvider: { type: String, enum: ['google-drive', 'local'], default: 'local' },
    storageStatus: { type: String, enum: ['AVAILABLE', 'MISSING', 'UPLOAD_FAILED'], default: 'AVAILABLE' },
    isPublished: { type: Boolean, default: true },
  },
  { timestamps: true }
);

export const BookModel = mongoose.models.Book || mongoose.model<IBook>('Book', BookSchema);

export const SEED_BOOKS: any[] = [
  {
    id: 'book-db-mig-14mb',
    title: 'Database Migration Tool',
    author: 'BWNHMCH Systems Administrator',
    publisher: 'BWNHMCH Academic Press',
    category: 'Systems & Infrastructure',
    department: 'Organon of Medicine',
    semester: '1st BHMS',
    subject: 'Medical Informatics & Systems',
    year: '2025-2026',
    isbn: '978-8131909999',
    accessionNo: 'BHMC-DIG-14M',
    type: 'DOCUMENT',
    fileFormat: 'PDF',
    mimeType: 'application/pdf',
    availableCopies: 50,
    isBookmarked: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80',
    fileName: 'Database_Migration_Tool.pdf',
    uploadedBy: 'Faculty Administrator',
    uploadedByUserId: 'usr-fac-001',
    uploadedRole: 'Faculty',
    uploadedAt: '2026-08-11',
    viewsCount: 150,
    downloadsCount: 85,
    allowDownload: true,
    description: 'Complete 14.2 MB operational manual and migration documentation for BWNHMCH digital infrastructure.',
    fileSize: '14.2 MB',
    pageCount: 120,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
  {
    id: 'book-101',
    title: 'Organon of Medicine (6th Edition with Commentary)',
    author: 'Dr. Samuel Hahnemann',
    publisher: 'B. Jain Publishers',
    category: 'Organon & Philosophy',
    department: 'Organon of Medicine',
    semester: '1st BHMS',
    subject: 'Organon of Medicine',
    year: '2025-2026',
    isbn: '978-8131903215',
    accessionNo: 'BHMC-LIB-0042',
    type: 'BOOK',
    fileFormat: 'PDF',
    availableCopies: 12,
    isBookmarked: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=300&q=80',
    fileName: 'bhmch_organon_edition6.pdf',
    uploadedBy: 'Dr. R. N. Mukherjee',
    uploadedByUserId: 'usr-vp-001',
    uploadedRole: 'Vice Principal',
    uploadedAt: '2026-06-15',
    viewsCount: 342,
    downloadsCount: 189,
    allowDownload: true,
    description: 'Complete 6th edition of Hahnemannian Organon with footnoted commentary and miasmatic breakdown.',
    fileSize: '14.2 MB',
    pageCount: 384,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
  {
    id: 'book-102',
    title: 'Lectures on Homoeopathic Materia Medica Notes & Comparative Charts',
    author: 'Dr. Priyanka Maji',
    publisher: 'BHMC Academic Press',
    category: 'Materia Medica',
    department: 'Materia Medica',
    semester: '2nd BHMS',
    subject: 'Materia Medica',
    year: '2025-2026',
    isbn: '978-8131900146',
    accessionNo: 'BHMC-LIB-0189',
    type: 'NOTES',
    fileFormat: 'PDF',
    availableCopies: 8,
    isBookmarked: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=300&q=80',
    fileName: 'bhmch_materia_medica_notes.pdf',
    uploadedBy: 'Dr. Priyanka Maji',
    uploadedByUserId: 'usr-fac-001',
    uploadedRole: 'HOD Materia Medica',
    uploadedAt: '2026-05-20',
    viewsCount: 512,
    downloadsCount: 290,
    allowDownload: true,
    description: 'In-depth notes on Polycrest remedies with keynote comparative symptom tables.',
    fileSize: '12.6 MB',
    pageCount: 240,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
  {
    id: 'book-103',
    title: 'Kent Repertory Methodologies & Repertorization Worksheets',
    author: 'Dr. Debabrata Sen',
    publisher: 'BHMC Central Press',
    category: 'Repertory',
    department: 'Repertory',
    semester: '3rd BHMS',
    subject: 'Repertory',
    year: '2025-2026',
    isbn: '978-8131902003',
    accessionNo: 'BHMC-LIB-0312',
    type: 'PRESENTATION',
    fileFormat: 'PDF',
    availableCopies: 15,
    isBookmarked: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=300&q=80',
    fileName: 'bhmch_repertory_worksheets.pdf',
    uploadedBy: 'Dr. Debabrata Sen',
    uploadedByUserId: 'usr-fac-009',
    uploadedRole: 'Associate Professor',
    uploadedAt: '2026-04-10',
    viewsCount: 215,
    downloadsCount: 98,
    allowDownload: true,
    description: 'Slide presentation on cross-referencing rubrics, gradation rules, and computer-aided repertorization.',
    fileSize: '10.8 MB',
    pageCount: 180,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
  {
    id: 'book-104',
    title: 'Homoeopathic Pharmacopoeia of India (HPI Vol I - X Official Guidelines)',
    author: 'Central Council for Research in Homoeopathy',
    publisher: 'Ministry of AYUSH Govt. of India',
    category: 'Homoeopathic Pharmacy',
    department: 'Homoeopathic Pharmacy',
    semester: '1st BHMS',
    subject: 'Homoeopathic Pharmacy',
    year: '2025-2026',
    isbn: '978-9388902113',
    accessionNo: 'BHMC-DIG-008',
    type: 'DOCUMENT',
    fileFormat: 'PDF',
    availableCopies: 25,
    isBookmarked: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=300&q=80',
    fileName: 'bhmch_hpi_guidelines.pdf',
    uploadedBy: 'Dr. Subhashish Pal',
    uploadedByUserId: 'usr-fac-012',
    uploadedRole: 'Pharmacy HOD',
    uploadedAt: '2026-03-01',
    viewsCount: 680,
    downloadsCount: 420,
    allowDownload: true,
    description: 'Standard drug preparation, vehicle purity standards, scales of potentization and Mother Tincture assays.',
    fileSize: '14.4 MB',
    pageCount: 150,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
  {
    id: 'book-105',
    title: 'Indian Journal of Research in Homoeopathy (IJRH) Special Clinical Issue 2026',
    author: 'CCRH Editorial Board',
    publisher: 'Central Council for Research in Homoeopathy',
    category: 'Research Journal',
    department: 'Research & Clinical Development',
    semester: 'Postgraduate',
    subject: 'Research Methodology',
    year: '2026',
    isbn: 'ISSN: 0974-7168',
    accessionNo: 'BHMC-JRN-2026-02',
    type: 'JOURNAL',
    fileFormat: 'PDF',
    availableCopies: 50,
    isBookmarked: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=300&q=80',
    fileName: 'bhmch_ijrh_research_special.pdf',
    uploadedBy: 'Dr. Susmita Chatterjee',
    uploadedByUserId: 'usr-prin-001',
    uploadedRole: 'Principal',
    uploadedAt: '2026-02-28',
    viewsCount: 890,
    downloadsCount: 512,
    allowDownload: true,
    description: 'Peer-reviewed research trials on high-potency ultra-dilutions in chronic autoimmune conditions.',
    fileSize: '12.5 MB',
    pageCount: 95,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
  {
    id: 'book-106',
    title: 'Anatomy Dissection & Histology Manual for BHMS Scholars',
    author: 'Dr. Ananya Roy',
    publisher: 'BHMCH Anatomy Department',
    category: 'Anatomy & Physiology',
    department: 'Anatomy',
    semester: '1st BHMS',
    subject: 'Anatomy',
    year: '2025-2026',
    isbn: '978-9388902724',
    accessionNo: 'BHMC-DIG-014',
    type: 'NOTES',
    fileFormat: 'PDF',
    availableCopies: 50,
    isBookmarked: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=300&q=80',
    fileName: 'bhmch_anatomy_dissection_guide.pdf',
    uploadedBy: 'Dr. Ananya Roy',
    uploadedByUserId: 'usr-fac-015',
    uploadedRole: 'Demonstrator',
    uploadedAt: '2026-02-14',
    viewsCount: 410,
    downloadsCount: 210,
    allowDownload: true,
    description: 'Illustrated guide covering head, neck, brain & neuroanatomy structures with clinical correlations.',
    fileSize: '18.5 MB',
    pageCount: 110,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
  {
    id: 'book-107',
    title: 'Clinical Miasmatic Manual & Chronic Disease Management',
    author: 'Dr. Subrata Kumar Banerjea',
    publisher: 'B. Jain Publishers',
    category: 'Practice of Medicine',
    department: 'Practice of Medicine',
    semester: '4th BHMS',
    subject: 'Practice of Medicine',
    year: '2025-2026',
    isbn: '978-8131908814',
    accessionNo: 'BHMC-LIB-0488',
    type: 'BOOK',
    fileFormat: 'PDF',
    availableCopies: 10,
    isBookmarked: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=300&q=80',
    fileName: 'bhmch_clinical_miasmatic_manual.pdf',
    uploadedBy: 'Dr. Amitav Roy',
    uploadedByUserId: 'usr-sup-001',
    uploadedRole: 'Medical Superintendent',
    uploadedAt: '2026-01-10',
    viewsCount: 620,
    downloadsCount: 340,
    allowDownload: true,
    description: 'Practical diagnosis of Psora, Sycosis, and Syphilis in modern OPD practice.',
    fileSize: '10.8 MB',
    pageCount: 165,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
  {
    id: 'book-108',
    title: 'Central Library Resource Directory & Digital Index 2026',
    author: 'BHMCH Library Board',
    publisher: 'BHMCH Central Library',
    category: 'Institutional Archives',
    department: 'General Academic',
    semester: 'All Semesters',
    subject: 'General Knowledge',
    year: '2026',
    isbn: 'N/A-BHMCH-2026',
    accessionNo: 'BHMC-DIG-001',
    type: 'DOCUMENT',
    fileFormat: 'PDF',
    availableCopies: 100,
    isBookmarked: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=300&q=80',
    fileName: 'bhmch_library_resource.pdf',
    uploadedBy: 'Central Library Staff',
    uploadedByUserId: 'usr-lib-002',
    uploadedRole: 'Librarian',
    uploadedAt: '2026-01-01',
    viewsCount: 1200,
    downloadsCount: 780,
    allowDownload: true,
    description: 'Index of all physical textbooks, rare manuscripts, and e-learning resources available in BHMCH library.',
    fileSize: '10.7 MB',
    pageCount: 45,
    storageProvider: 'local',
    storageStatus: 'AVAILABLE',
    isPublished: true,
  },
];
