import mongoose, { Schema, Document } from 'mongoose';

export interface IStaff extends Document {
  id: string;
  slNo: number;
  empId: string;
  name: string;
  roleCategory: 'MEDICAL_STAFF' | 'OFFICE_STAFF' | 'PARAMEDICAL_STAFF' | 'NON_MEDICAL_STAFF';
  department: string;
  designation: string;
  category: string;
  displayOrder: number;
  qualification?: string;
  contactNumber?: string;
  email?: string;
  photoUrl?: string;
  photo?: {
    driveFileId: string;
    fileName: string;
    mimeType: string;
  };
  registrationNumber?: string;
  joiningDate?: string;
  promotionDate?: string;
  experienceYears?: string;
  specialization?: string;
  biography?: string;
  availability?: string;
  dutyShift?: string;
  opdCounter?: string;
  status: 'ACTIVE' | 'INACTIVE';
  joiningYear?: number;
  createdAt?: string;
  updatedAt?: string;
}

const StaffSchema = new Schema<IStaff>(
  {
    id: { type: String, required: true, unique: true },
    slNo: { type: Number, required: true },
    empId: { type: String, required: true },
    name: { type: String, required: true, trim: true },
    roleCategory: {
      type: String,
      required: true,
      enum: ['MEDICAL_STAFF', 'OFFICE_STAFF', 'PARAMEDICAL_STAFF', 'NON_MEDICAL_STAFF'],
      default: 'OFFICE_STAFF',
    },
    department: { type: String, required: true, trim: true },
    designation: { type: String, required: true, trim: true },
    category: { type: String, required: true, trim: true, default: 'STAFF' },
    displayOrder: { type: Number, required: true, index: true },
    qualification: { type: String },
    contactNumber: { type: String },
    email: { type: String },
    photoUrl: { type: String },
    photo: {
      driveFileId: { type: String },
      fileName: { type: String },
      mimeType: { type: String },
    },
    registrationNumber: { type: String },
    joiningDate: { type: String },
    promotionDate: { type: String },
    experienceYears: { type: String },
    specialization: { type: String },
    biography: { type: String },
    availability: { type: String, default: 'AVAILABLE' },
    dutyShift: { type: String },
    opdCounter: { type: String },
    status: { type: String, enum: ['ACTIVE', 'INACTIVE'], default: 'ACTIVE' },
    joiningYear: { type: Number },
  },
  { timestamps: true, strict: false }
);

export const StaffModel = mongoose.models.Staff || mongoose.model<IStaff>('Staff', StaffSchema);

export const SEED_STAFF = [
  {
    "id": "f-org-1",
    "slNo": 1,
    "empId": "EMP-ORG-001",
    "name": "Dr. Abhijit Chatterjee",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Organon of Medicine",
    "departmentId": "org",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 1,
    "qualification": "M.D. (Hom.)",
    "specialization": "Organon of Medicine & Philosophy",
    "email": "abhijit.chatterjee@bhmch.ac.in",
    "phone": "+91 98310 12345",
    "contactNumber": "+91 98310 12345",
    "registrationNumber": "WB-NCH-1995-012",
    "joiningDate": "2005-08-01",
    "promotionDate": "2018-01-15",
    "experienceYears": "18+ Years",
    "biography": "Senior Professor & HOD.",
    "status": "ACTIVE",
    "photoUrl": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400"
  },
  {
    "id": "f-org-2",
    "slNo": 2,
    "empId": "EMP-ORG-002",
    "name": "Dr. Aditi Biswas",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Organon of Medicine",
    "departmentId": "org",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 2,
    "qualification": "M.D. (Hom.)",
    "specialization": "Miasmatic Diagnosis",
    "email": "aditi.biswas@bhmch.ac.in",
    "phone": "+91 98310 23456",
    "contactNumber": "+91 98310 23456",
    "registrationNumber": "WB-NCH-2002-045",
    "joiningDate": "2010-09-15",
    "promotionDate": "2020-04-10",
    "experienceYears": "13+ Years",
    "biography": "Specialist in miasmatic clinical diagnosis.",
    "status": "ACTIVE",
    "photoUrl": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400"
  },
  {
    "id": "f-mm-1",
    "slNo": 3,
    "empId": "EMP-MM-001",
    "name": "Dr. Anisa Afroz",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Homoeopathic Materia Medica",
    "departmentId": "mm",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 3,
    "qualification": "M.D. (Hom.)",
    "specialization": "Comparative Materia Medica",
    "email": "anisa.afroz@bhmch.ac.in",
    "phone": "+91 98310 34567",
    "contactNumber": "+91 98310 34567",
    "registrationNumber": "WB-NCH-1998-089",
    "joiningDate": "2007-03-01",
    "promotionDate": "2019-06-01",
    "experienceYears": "16+ Years",
    "biography": "Leading expert in Materia Medica.",
    "status": "ACTIVE",
    "photoUrl": "https://images.unsplash.com/photo-1594824813566-88855ce7890b?auto=format&fit=crop&q=80&w=400"
  },
  {
    "id": "f-pharm-1",
    "slNo": 4,
    "empId": "EMP-PHARM-001",
    "name": "Dr. Arindam Roy",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Homoeopathic Pharmacy",
    "departmentId": "pharm",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 4,
    "qualification": "M.D. (Hom.)",
    "specialization": "Pharmacognosy & Potentisation",
    "email": "arindam.roy@bhmch.ac.in",
    "phone": "+91 98310 45678",
    "contactNumber": "+91 98310 45678",
    "registrationNumber": "WB-NCH-2006-112",
    "joiningDate": "2014-11-20",
    "promotionDate": "2021-08-15",
    "experienceYears": "9+ Years",
    "biography": "Pharmacognosy researcher.",
    "status": "ACTIVE",
    "photoUrl": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400"
  },
  {
    "id": "f-pm-1",
    "slNo": 5,
    "empId": "EMP-PM-001",
    "name": "Dr. Ashis Biswas",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Practice of Medicine",
    "departmentId": "pm",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 5,
    "qualification": "M.D. (Hom.)",
    "specialization": "Clinical Therapeutics",
    "email": "ashis.biswas@bhmch.ac.in",
    "phone": "+91 98310 56789",
    "contactNumber": "+91 98310 56789",
    "registrationNumber": "WB-NCH-2004-078",
    "joiningDate": "2012-01-10",
    "promotionDate": "2022-03-01",
    "experienceYears": "11+ Years",
    "biography": "Clinical Therapeutics specialist.",
    "status": "ACTIVE",
    "photoUrl": "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=400"
  },
  {
    "id": "f-cm-1",
    "slNo": 6,
    "empId": "EMP-CM-001",
    "name": "Dr. Ashish Sarkar",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Community Medicine",
    "departmentId": "cm",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 6,
    "qualification": "M.D. (Hom.)",
    "specialization": "Epidemiology & Preventive Care",
    "email": "ashish.sarkar@bhmch.ac.in",
    "phone": "+91 98310 67890",
    "contactNumber": "+91 98310 67890",
    "registrationNumber": "WB-NCH-2009-156",
    "joiningDate": "2016-07-01",
    "promotionDate": "2023-01-10",
    "experienceYears": "7+ Years",
    "biography": "Epidemiology and public health expert.",
    "status": "ACTIVE",
    "photoUrl": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400"
  },
  {
    "id": "f-rep-1",
    "slNo": 7,
    "empId": "EMP-REP-001",
    "name": "Dr. Ashok Kr. Bhattacherjee",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Case Taking & Repertory",
    "departmentId": "rep",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 7,
    "qualification": "M.D. (Hom.)",
    "specialization": "Computer Repertorization",
    "email": "ashok.bhattacherjee@bhmch.ac.in",
    "phone": "+91 98310 78901",
    "contactNumber": "+91 98310 78901",
    "registrationNumber": "WB-NCH-1992-005",
    "joiningDate": "2002-04-15",
    "promotionDate": "2015-05-20",
    "experienceYears": "21+ Years",
    "biography": "Pioneer in computer repertorization.",
    "status": "ACTIVE",
    "photoUrl": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400"
  },
  {
    "id": "f-org-3",
    "slNo": 8,
    "empId": "EMP-ORG-003",
    "name": "Dr. Swapan Kundu",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Organon of Medicine",
    "departmentId": "org",
    "designation": "Guest Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 8,
    "qualification": "B.H.M.S ; M.D. (HOM)",
    "specialization": "Chronic Diseases",
    "email": "drswapankundu@gmail.com",
    "phone": "+91 9830254112",
    "contactNumber": "+91 9830254112",
    "registrationNumber": "18234",
    "joiningDate": "2015-01-10",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-org-4",
    "slNo": 9,
    "empId": "EMP-ORG-004",
    "name": "Dr. Dhananjaya Chatterjee",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Organon of Medicine",
    "departmentId": "org",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 9,
    "qualification": "B.H.M.S ; M.D. (ORGANON)",
    "specialization": "Organon Philosophy",
    "email": "drdhananjaya@gmail.com",
    "phone": "+91 9433128904",
    "contactNumber": "+91 9433128904",
    "registrationNumber": "21450",
    "joiningDate": "2018-05-20",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-org-5",
    "slNo": 10,
    "empId": "EMP-ORG-005",
    "name": "Dr. Suhisna Das",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Organon of Medicine",
    "departmentId": "org",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 10,
    "qualification": "B.H.M.S ; M.D. (HOM)",
    "specialization": "Vital Force Analysis",
    "email": "suhisna.das@gmail.com",
    "phone": "+91 9874561230",
    "contactNumber": "+91 9874561230",
    "registrationNumber": "29870",
    "joiningDate": "2021-08-14",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-org-6",
    "slNo": 11,
    "empId": "EMP-ORG-006",
    "name": "Susmita Dey",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Organon of Medicine",
    "departmentId": "org",
    "designation": "Lecturer",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 11,
    "qualification": "B.H.M.S",
    "specialization": "Organon Fundamentals",
    "email": "susmitadey@gmail.com",
    "phone": "+91 9123456789",
    "contactNumber": "+91 9123456789",
    "registrationNumber": "31200",
    "joiningDate": "2023-02-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-anat-1",
    "slNo": 12,
    "empId": "EMP-ANAT-001",
    "name": "Dr. Prasenjit Biswas",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Anatomy & Histology",
    "departmentId": "anat",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 12,
    "qualification": "M.D. (Hom.), MS (Anat)",
    "specialization": "Gross Anatomy",
    "email": "prasenjit.biswas@bhmch.ac.in",
    "phone": "+91 9830112233",
    "contactNumber": "+91 9830112233",
    "registrationNumber": "20101",
    "joiningDate": "2008-03-12",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-anat-2",
    "slNo": 13,
    "empId": "EMP-ANAT-002",
    "name": "Dr. Nipa Sardar",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Anatomy & Histology",
    "departmentId": "anat",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 13,
    "qualification": "M.D. (Hom.)",
    "specialization": "Histology",
    "email": "nipa.sardar@bhmch.ac.in",
    "phone": "+91 9830223344",
    "contactNumber": "+91 9830223344",
    "registrationNumber": "24510",
    "joiningDate": "2015-09-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-anat-3",
    "slNo": 14,
    "empId": "EMP-ANAT-003",
    "name": "Dr. Ayon Das",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Anatomy & Histology",
    "departmentId": "anat",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 14,
    "qualification": "B.H.M.S, M.D.",
    "specialization": "Embryology",
    "email": "ayon.das@bhmch.ac.in",
    "phone": "+91 9830334455",
    "contactNumber": "+91 9830334455",
    "registrationNumber": "28900",
    "joiningDate": "2019-11-15",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-phys-1",
    "slNo": 15,
    "empId": "EMP-PHYS-001",
    "name": "Dr. Santosh Kumar",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Physiology including Biochemistry",
    "departmentId": "phys",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 15,
    "qualification": "M.D. (Hom.)",
    "specialization": "Systemic Physiology",
    "email": "santosh.kumar@bhmch.ac.in",
    "phone": "+91 9830445566",
    "contactNumber": "+91 9830445566",
    "registrationNumber": "19800",
    "joiningDate": "2006-02-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-phys-2",
    "slNo": 16,
    "empId": "EMP-PHYS-002",
    "name": "Dr. Mansur Habibullah Gazi",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Physiology including Biochemistry",
    "departmentId": "phys",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 16,
    "qualification": "M.D. (Hom.)",
    "specialization": "Neurophysiology",
    "email": "mansur.gazi@bhmch.ac.in",
    "phone": "+91 9830556677",
    "contactNumber": "+91 9830556677",
    "registrationNumber": "23410",
    "joiningDate": "2013-04-10",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-phys-3",
    "slNo": 17,
    "empId": "EMP-PHYS-003",
    "name": "Dr. Kousttav Sarkar",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Physiology including Biochemistry",
    "departmentId": "phys",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 17,
    "qualification": "M.D. (Hom.)",
    "specialization": "Biochemistry",
    "email": "kousttav.sarkar@bhmch.ac.in",
    "phone": "+91 9830667788",
    "contactNumber": "+91 9830667788",
    "registrationNumber": "27890",
    "joiningDate": "2018-07-20",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-pharm-2",
    "slNo": 18,
    "empId": "EMP-PHARM-002",
    "name": "Dr. Soumalya Golder",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Homoeopathic Pharmacy",
    "departmentId": "pharm",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 18,
    "qualification": "M.D. (Hom.)",
    "specialization": "Pharmacy Practice",
    "email": "soumalya.golder@bhmch.ac.in",
    "phone": "+91 9830778899",
    "contactNumber": "+91 9830778899",
    "registrationNumber": "25670",
    "joiningDate": "2016-01-15",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-path-1",
    "slNo": 19,
    "empId": "EMP-PATH-001",
    "name": "Dr. Santanu Mukherjee",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Pathology, Microbiology & Parasitology",
    "departmentId": "path",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 19,
    "qualification": "M.D. (Hom.)",
    "specialization": "General Pathology",
    "email": "santanu.mukherjee@bhmch.ac.in",
    "phone": "+91 9830889900",
    "contactNumber": "+91 9830889900",
    "registrationNumber": "18900",
    "joiningDate": "2005-06-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-path-2",
    "slNo": 20,
    "empId": "EMP-PATH-002",
    "name": "Dr. Debasish Sarker",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Pathology, Microbiology & Parasitology",
    "departmentId": "path",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 20,
    "qualification": "M.D. (Hom.)",
    "specialization": "Microbiology",
    "email": "debasish.sarker@bhmch.ac.in",
    "phone": "+91 9830990011",
    "contactNumber": "+91 9830990011",
    "registrationNumber": "26780",
    "joiningDate": "2017-09-10",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-fmt-1",
    "slNo": 21,
    "empId": "EMP-FMT-001",
    "name": "Dr. Enamul Haque",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Forensic Medicine & Toxicology",
    "departmentId": "fmt",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 21,
    "qualification": "M.D. (Hom.)",
    "specialization": "Medical Jurisprudence",
    "email": "enamul.haque@bhmch.ac.in",
    "phone": "+91 9831001122",
    "contactNumber": "+91 9831001122",
    "registrationNumber": "19200",
    "joiningDate": "2004-03-15",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-fmt-2",
    "slNo": 22,
    "empId": "EMP-FMT-002",
    "name": "Dr. Abdul Gaffar",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Forensic Medicine & Toxicology",
    "departmentId": "fmt",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 22,
    "qualification": "M.D. (Hom.)",
    "specialization": "Toxicology",
    "email": "abdul.gaffar@bhmch.ac.in",
    "phone": "+91 9831112233",
    "contactNumber": "+91 9831112233",
    "registrationNumber": "27810",
    "joiningDate": "2018-10-05",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-gyn-1",
    "slNo": 23,
    "empId": "EMP-GYN-001",
    "name": "Prof. (Dr.) Pronab Bhattacherjee",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Obstetrics, Gynecology & Neonatology",
    "departmentId": "gyn",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 23,
    "qualification": "M.D. (Hom.)",
    "specialization": "Obstetrics & Gynaecology",
    "email": "pronab.bhattacherjee@bhmch.ac.in",
    "phone": "+91 9831223344",
    "contactNumber": "+91 9831223344",
    "registrationNumber": "17800",
    "joiningDate": "2001-01-10",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-gyn-2",
    "slNo": 24,
    "empId": "EMP-GYN-002",
    "name": "Dr. Debasish Chakraborty",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Obstetrics, Gynecology & Neonatology",
    "departmentId": "gyn",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 24,
    "qualification": "M.D. (Hom.)",
    "specialization": "Gynaecological Therapeutics",
    "email": "debasish.c@bhmch.ac.in",
    "phone": "+91 9831334455",
    "contactNumber": "+91 9831334455",
    "registrationNumber": "22340",
    "joiningDate": "2011-05-20",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-gyn-3",
    "slNo": 25,
    "empId": "EMP-GYN-003",
    "name": "Dr. Sharmistha Nandi",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Obstetrics, Gynecology & Neonatology",
    "departmentId": "gyn",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 25,
    "qualification": "M.D. (Hom.)",
    "specialization": "Neonatology",
    "email": "sharmistha.nandi@bhmch.ac.in",
    "phone": "+91 9831445566",
    "contactNumber": "+91 9831445566",
    "registrationNumber": "28912",
    "joiningDate": "2019-03-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-gyn-4",
    "slNo": 26,
    "empId": "EMP-GYN-004",
    "name": "Dr. Tapan Kumar Bandyopadhyay",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Obstetrics, Gynecology & Neonatology",
    "departmentId": "gyn",
    "designation": "Visiting Specialist",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 26,
    "qualification": "M.B.B.S, D.G.O.",
    "specialization": "Gynaecology Surgery",
    "email": "tapan.bandyopadhyay@bhmch.ac.in",
    "phone": "+91 9831556677",
    "contactNumber": "+91 9831556677",
    "registrationNumber": "15600",
    "joiningDate": "2005-07-15",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-surg-1",
    "slNo": 27,
    "empId": "EMP-SURG-001",
    "name": "Dr. Sushil Murmu",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Surgery & Allied Specialties",
    "departmentId": "surg",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 27,
    "qualification": "M.D. (Hom.), MS",
    "specialization": "Homoeopathic Surgery",
    "email": "sushil.murmu@bhmch.ac.in",
    "phone": "+91 9831667788",
    "contactNumber": "+91 9831667788",
    "registrationNumber": "18950",
    "joiningDate": "2003-08-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-surg-2",
    "slNo": 28,
    "empId": "EMP-SURG-002",
    "name": "Prof. (Dr.) Susmita Chatterjee",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Surgery & Allied Specialties",
    "departmentId": "surg",
    "designation": "Superintendent & Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 28,
    "qualification": "M.D. (Hom.)",
    "specialization": "Clinical Surgery",
    "email": "susmita.chatterjee@bhmch.ac.in",
    "phone": "+91 9831778899",
    "contactNumber": "+91 9831778899",
    "registrationNumber": "16700",
    "joiningDate": "2000-02-15",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-surg-3",
    "slNo": 29,
    "empId": "EMP-SURG-003",
    "name": "Dr. Chinmoy Sarkar",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Surgery & Allied Specialties",
    "departmentId": "surg",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 29,
    "qualification": "M.D. (Hom.)",
    "specialization": "Operative Therapeutics",
    "email": "chinmoy.sarkar@bhmch.ac.in",
    "phone": "+91 9831889900",
    "contactNumber": "+91 9831889900",
    "registrationNumber": "23450",
    "joiningDate": "2012-11-10",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-surg-4",
    "slNo": 30,
    "empId": "EMP-SURG-004",
    "name": "Dr. Prithish Mukherjee",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Surgery & Allied Specialties",
    "departmentId": "surg",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 30,
    "qualification": "B.D.S, M.D.",
    "specialization": "Dental Surgery",
    "email": "prithish.mukherjee@bhmch.ac.in",
    "phone": "+91 9831990011",
    "contactNumber": "+91 9831990011",
    "registrationNumber": "29010",
    "joiningDate": "2020-01-20",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-surg-5",
    "slNo": 31,
    "empId": "EMP-SURG-005",
    "name": "Dr. Kazi Toufik Ali",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Surgery & Allied Specialties",
    "departmentId": "surg",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 31,
    "qualification": "M.D. (Hom.)",
    "specialization": "General Surgery",
    "email": "kazi.toufik@bhmch.ac.in",
    "phone": "+91 9832001122",
    "contactNumber": "+91 9832001122",
    "registrationNumber": "30120",
    "joiningDate": "2021-06-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-surg-6",
    "slNo": 32,
    "empId": "EMP-SURG-006",
    "name": "Dr. Sk. Gousul Azam",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Surgery & Allied Specialties",
    "departmentId": "surg",
    "designation": "Lecturer",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 32,
    "qualification": "B.H.M.S.",
    "specialization": "Surgical Care",
    "email": "gousul.azam@bhmch.ac.in",
    "phone": "+91 9832112233",
    "contactNumber": "+91 9832112233",
    "registrationNumber": "31890",
    "joiningDate": "2023-04-10",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-surg-7",
    "slNo": 33,
    "empId": "EMP-SURG-007",
    "name": "Dr. Asim Kumar Das",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Surgery & Allied Specialties",
    "departmentId": "surg",
    "designation": "Visiting Specialist",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 33,
    "qualification": "M.S. (Surgery)",
    "specialization": "Surgical Procedures",
    "email": "asim.das@bhmch.ac.in",
    "phone": "+91 9832223344",
    "contactNumber": "+91 9832223344",
    "registrationNumber": "14500",
    "joiningDate": "2007-09-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-pm-2",
    "slNo": 34,
    "empId": "EMP-PM-002",
    "name": "Dr. Soumitra De",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Practice of Medicine",
    "departmentId": "pm",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 34,
    "qualification": "M.D. (Hom.)",
    "specialization": "Clinical Medicine",
    "email": "soumitra.de@bhmch.ac.in",
    "phone": "+91 9832334455",
    "contactNumber": "+91 9832334455",
    "registrationNumber": "18100",
    "joiningDate": "2002-12-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-pm-3",
    "slNo": 35,
    "empId": "EMP-PM-003",
    "name": "Shilpa Mondal",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Practice of Medicine",
    "departmentId": "pm",
    "designation": "Lecturer",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 35,
    "qualification": "B.H.M.S.",
    "specialization": "Internal Medicine",
    "email": "shilpa.mondal@bhmch.ac.in",
    "phone": "+91 9832445566",
    "contactNumber": "+91 9832445566",
    "registrationNumber": "32100",
    "joiningDate": "2023-08-15",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-pm-4",
    "slNo": 36,
    "empId": "EMP-PM-004",
    "name": "Dr. Kousick Mati",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Practice of Medicine",
    "departmentId": "pm",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 36,
    "qualification": "M.D. (Hom.)",
    "specialization": "Cardiology & Medicine",
    "email": "kousick.mati@bhmch.ac.in",
    "phone": "+91 9832556677",
    "contactNumber": "+91 9832556677",
    "registrationNumber": "29810",
    "joiningDate": "2020-05-10",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-cm-2",
    "slNo": 37,
    "empId": "EMP-CM-002",
    "name": "Dr. Sourav Kr. Sarkar",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Community Medicine",
    "departmentId": "cm",
    "designation": "Professor & HOD",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 37,
    "qualification": "M.D. (Hom.)",
    "specialization": "Public Health",
    "email": "sourav.sarkar@bhmch.ac.in",
    "phone": "+91 9832667788",
    "contactNumber": "+91 9832667788",
    "registrationNumber": "19500",
    "joiningDate": "2004-10-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-cm-3",
    "slNo": 38,
    "empId": "EMP-CM-003",
    "name": "Prof. (Dr.) Asim Kumar Samanta",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Community Medicine",
    "departmentId": "cm",
    "designation": "Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 38,
    "qualification": "M.D. (Hom.)",
    "specialization": "Community Hygiene",
    "email": "asim.samanta@bhmch.ac.in",
    "phone": "+91 9832778899",
    "contactNumber": "+91 9832778899",
    "registrationNumber": "16200",
    "joiningDate": "1999-04-15",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-mm-2",
    "slNo": 39,
    "empId": "EMP-MM-002",
    "name": "Dr. Priyanka Maji",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Homoeopathic Materia Medica",
    "departmentId": "mm",
    "designation": "Associate Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 39,
    "qualification": "M.D. (Hom.)",
    "specialization": "Drug Proving",
    "email": "priyanka.maji@bhmch.ac.in",
    "phone": "+91 9832889900",
    "contactNumber": "+91 9832889900",
    "registrationNumber": "24100",
    "joiningDate": "2014-06-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-mm-3",
    "slNo": 40,
    "empId": "EMP-MM-003",
    "name": "Dr. Nabanita Kundu",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Homoeopathic Materia Medica",
    "departmentId": "mm",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 40,
    "qualification": "M.D. (Hom.)",
    "specialization": "Materia Medica",
    "email": "nabanita.kundu@bhmch.ac.in",
    "phone": "+91 9832990011",
    "contactNumber": "+91 9832990011",
    "registrationNumber": "32635",
    "joiningDate": "2024-05-15",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-mm-4",
    "slNo": 41,
    "empId": "EMP-MM-004",
    "name": "Dr. Dipa Kundu",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Homoeopathic Materia Medica",
    "departmentId": "mm",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 41,
    "qualification": "M.D. (Hom.)",
    "specialization": "Pharmacodynamics",
    "email": "dipa.kundu@bhmch.ac.in",
    "phone": "+91 9833001122",
    "contactNumber": "+91 9833001122",
    "registrationNumber": "32831",
    "joiningDate": "2026-01-29",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-rep-2",
    "slNo": 42,
    "empId": "EMP-REP-002",
    "name": "Dr. Shimul Das",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Case Taking & Repertory",
    "departmentId": "rep",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 42,
    "qualification": "M.D. (Hom.)",
    "specialization": "Repertorization",
    "email": "shimul.das@bhmch.ac.in",
    "phone": "+91 9833112233",
    "contactNumber": "+91 9833112233",
    "registrationNumber": "29965",
    "joiningDate": "2023-06-05",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-rep-3",
    "slNo": 43,
    "empId": "EMP-REP-003",
    "name": "Dr. Soumyadip Pal",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Case Taking & Repertory",
    "departmentId": "rep",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 43,
    "qualification": "M.D. (Hom.)",
    "specialization": "RadarOpus Software",
    "email": "soumyadip.pal@bhmch.ac.in",
    "phone": "+91 9833223344",
    "contactNumber": "+91 9833223344",
    "registrationNumber": "32947",
    "joiningDate": "2025-07-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "f-rep-4",
    "slNo": 44,
    "empId": "EMP-REP-004",
    "name": "Dr. Abdul Hakim Sk.",
    "roleCategory": "MEDICAL_STAFF",
    "department": "Case Taking & Repertory",
    "departmentId": "rep",
    "designation": "Assistant Professor",
    "category": "ACADEMIC FACULTY",
    "displayOrder": 44,
    "qualification": "M.D. (Hom.)",
    "specialization": "Symptom Totality",
    "email": "abdul.hakim@bhmch.ac.in",
    "phone": "+91 9833334455",
    "contactNumber": "+91 9833334455",
    "registrationNumber": "33036",
    "joiningDate": "2025-07-01",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-036",
    "slNo": 45,
    "empId": "SL-37",
    "name": "AMIT DHANK",
    "roleCategory": "OFFICE_STAFF",
    "department": "OFFICE STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-off",
    "designation": "WARD BOY",
    "category": "OFFICE STAFF",
    "displayOrder": 45,
    "qualification": "Higher Secondary",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-012",
    "slNo": 46,
    "empId": "SL-14",
    "name": "ANAESTHETIST. (ON CALL)",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "ANAESTHETIST",
    "category": "MEDICAL STAFF",
    "displayOrder": 46,
    "qualification": "M.D. (Anaesthesia)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-017",
    "slNo": 47,
    "empId": "SL-18",
    "name": "ARUNIMA LAHA.",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "DIETICIAN",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 47,
    "qualification": "B.Sc (Nutrition)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-043",
    "slNo": 48,
    "empId": "SL-44",
    "name": "AWADHESH KUMAR MAHATO",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "MEDICAL LABORATORY TECHNICIAN",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 48,
    "qualification": "D.M.L.T",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-034",
    "slNo": 49,
    "empId": "SL-35",
    "name": "BRISHTI DAS",
    "roleCategory": "OFFICE_STAFF",
    "department": "OFFICE STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-off",
    "designation": "AYA",
    "category": "OFFICE STAFF",
    "displayOrder": 49,
    "qualification": "Secondary",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-029",
    "slNo": 50,
    "empId": "SL-30",
    "name": "CHAINA GHOSH",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "O.T. ASSISTANT.",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 50,
    "qualification": "D.O.T.T",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-008",
    "slNo": 51,
    "empId": "SL-09",
    "name": "CHANDRA DAS",
    "roleCategory": "OFFICE_STAFF",
    "department": "OFFICE STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-off",
    "designation": "L.D.C (REGISTRATION CLERK)",
    "category": "OFFICE STAFF",
    "displayOrder": 51,
    "qualification": "B.Com",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-009",
    "slNo": 52,
    "empId": "SL-10",
    "name": "PUSPA DEY",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "STAFF NURSE.",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 52,
    "qualification": "G.N.M.",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-013",
    "slNo": 53,
    "empId": "SL-15",
    "name": "DR ASITAVA MUKHERJEE",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "RADIOLOGIST",
    "category": "MEDICAL STAFF",
    "displayOrder": 53,
    "qualification": "M.D. (Radiology)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-014",
    "slNo": 54,
    "empId": "SL-16",
    "name": "DR. NILADRI MODOK.",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "SONOLOGIST",
    "category": "MEDICAL STAFF",
    "displayOrder": 54,
    "qualification": "M.B.B.S, D.M.R.D",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-016",
    "slNo": 55,
    "empId": "SL-17",
    "name": "SANDHYA DAS",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "STAFF NURSE.",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 55,
    "qualification": "G.N.M.",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-018",
    "slNo": 56,
    "empId": "SL-19",
    "name": "SUKDEV MUKHERJEE",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "PHYSIOTHERAPIST",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 56,
    "qualification": "B.P.T",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-019",
    "slNo": 57,
    "empId": "SL-20",
    "name": "SUNIL KUMAR SHAW",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "YOGA & NATUROPATHY",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 57,
    "qualification": "Diploma in Yoga",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-020",
    "slNo": 58,
    "empId": "SL-21",
    "name": "SWAPAN BARAL",
    "roleCategory": "OFFICE_STAFF",
    "department": "OFFICE STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-off",
    "designation": "DISPENSER",
    "category": "OFFICE STAFF",
    "displayOrder": 58,
    "qualification": "D.Pharm (Hom)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-021",
    "slNo": 59,
    "empId": "SL-22",
    "name": "UJJWAL KR. MONDAL",
    "roleCategory": "OFFICE_STAFF",
    "department": "OFFICE STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-off",
    "designation": "DISPENSER",
    "category": "OFFICE STAFF",
    "displayOrder": 59,
    "qualification": "D.Pharm (Hom)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-022",
    "slNo": 60,
    "empId": "SL-23",
    "name": "SHOUVIK PAL",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "UDC",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 60,
    "qualification": "Graduate",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-023",
    "slNo": 61,
    "empId": "SL-24",
    "name": "KALPANA GHOSAL",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "STAFF NURSE.",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 61,
    "qualification": "G.N.M.",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-024",
    "slNo": 62,
    "empId": "SL-25",
    "name": "SANCHITA DAS",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "L.D.C",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 62,
    "qualification": "Graduate",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-025",
    "slNo": 63,
    "empId": "SL-26",
    "name": "GEETA PAL",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "STAFF NURSE.",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 63,
    "qualification": "G.N.M.",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-026",
    "slNo": 64,
    "empId": "SL-27",
    "name": "SUMITA CHAKRABORTY",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "PUBLIC RELATION OFFICER",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 64,
    "qualification": "M.A. (PR)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-027",
    "slNo": 65,
    "empId": "SL-28",
    "name": "MAYUKH MUKHERJEE",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "USG ASSISTANT.",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 65,
    "qualification": "D.M.L.T",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-028",
    "slNo": 66,
    "empId": "SL-29",
    "name": "NIHAR KUMAR SANTRA",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "SECURITY.",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 66,
    "qualification": "Ex-Serviceman",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-030",
    "slNo": 67,
    "empId": "SL-31",
    "name": "RAHUL DAS",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "SECURITY GUARD",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 67,
    "qualification": "Secondary",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-031",
    "slNo": 68,
    "empId": "SL-32",
    "name": "SK. AKTAR",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "SWEEPER",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 68,
    "qualification": "Class VIII",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-032",
    "slNo": 69,
    "empId": "SL-33",
    "name": "TINA ROY",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "NURSING STAFF",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 69,
    "qualification": "B.Sc Nursing",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-033",
    "slNo": 70,
    "empId": "SL-34",
    "name": "RENUKA BARI",
    "roleCategory": "PARAMEDICAL_STAFF",
    "department": "PARA - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-para",
    "designation": "NURSING STAFF",
    "category": "PARAMEDICAL STAFF",
    "displayOrder": 70,
    "qualification": "G.N.M.",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-035",
    "slNo": 71,
    "empId": "SL-36",
    "name": "SARMISTHA DAS",
    "roleCategory": "OFFICE_STAFF",
    "department": "OFFICE STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-off",
    "designation": "AYA",
    "category": "OFFICE STAFF",
    "displayOrder": 71,
    "qualification": "Secondary",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-037",
    "slNo": 72,
    "empId": "SL-38",
    "name": "RINKU DEY",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "MULTI TASK STAFF",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 72,
    "qualification": "Class X",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-038",
    "slNo": 73,
    "empId": "SL-39",
    "name": "DULAL BOSE",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "WARD BOY",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 73,
    "qualification": "Class VIII",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-039",
    "slNo": 74,
    "empId": "SL-40",
    "name": "HIRALAL PRAMANIK",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "SECURITY GUARD",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 74,
    "qualification": "Ex-Serviceman",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-040",
    "slNo": 75,
    "empId": "SL-41",
    "name": "DEBDAS CAKRABORTY",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "SECURITY GUARD",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 75,
    "qualification": "Secondary",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-041",
    "slNo": 76,
    "empId": "SL-42",
    "name": "MOUMITA MAJI",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "YOGA EXPERT.",
    "category": "MEDICAL STAFF",
    "displayOrder": 76,
    "qualification": "M.Sc in Yoga",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-042",
    "slNo": 77,
    "empId": "SL-43",
    "name": "SHILPI DAS",
    "roleCategory": "NON_MEDICAL_STAFF",
    "department": "NON - MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-nonmed",
    "designation": "DRESSER",
    "category": "NON-MEDICAL STAFF",
    "displayOrder": 77,
    "qualification": "First Aid Certified",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-002",
    "slNo": 78,
    "empId": "SL-03",
    "name": "DR. PUSPENDU BISWAS.",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "SENIOR MEDICAL OFFICER",
    "category": "MEDICAL STAFF",
    "displayOrder": 78,
    "qualification": "M.D. (Hom.)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-003",
    "slNo": 79,
    "empId": "SL-04",
    "name": "DR. SOUMYA SAMANTA.",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "RESIDENTIAL MEDICAL OFFICER",
    "category": "MEDICAL STAFF",
    "displayOrder": 79,
    "qualification": "M.D. (Hom.)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-004",
    "slNo": 80,
    "empId": "SL-05",
    "name": "DR. ANUP PRASAD GUPTA",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "DEPUTY SUPERINTENDENT.",
    "category": "MEDICAL STAFF",
    "displayOrder": 80,
    "qualification": "M.D. (Hom.)",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-005",
    "slNo": 81,
    "empId": "SL-06",
    "name": "DR. SHYMASHREE PAL.",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "MEDICAL OFFICER",
    "category": "MEDICAL STAFF",
    "displayOrder": 81,
    "qualification": "B.H.M.S.",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-006",
    "slNo": 82,
    "empId": "SL-07",
    "name": "DR. BHUBANESWAR BHATTACHERJEE",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "CLINICAL BIO CHEMIST",
    "category": "MEDICAL STAFF",
    "displayOrder": 82,
    "qualification": "M.Sc (BioChem), Ph.D.",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  },
  {
    "id": "hs-007",
    "slNo": 83,
    "empId": "SL-08",
    "name": "DR. NAMRATA DAS",
    "roleCategory": "MEDICAL_STAFF",
    "department": "MEDICAL STAFF (HOSPITAL SECTION)",
    "departmentId": "hosp-med",
    "designation": "HOUSE PHYSICIAN",
    "category": "MEDICAL STAFF",
    "displayOrder": 83,
    "qualification": "B.H.M.S.",
    "specialization": "",
    "email": "",
    "phone": "",
    "contactNumber": "",
    "registrationNumber": "",
    "joiningDate": "",
    "promotionDate": "",
    "experienceYears": "",
    "biography": "",
    "status": "ACTIVE",
    "photoUrl": ""
  }
];
