services:
  - type: web
    name: smart-homeopathic-college-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    region: singapore
    plan: free
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CLIENT_URL
        value: https://bwnhmch-qu7p.vercel.app
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_DRIVE_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_DRIVE_PRIVATE_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
