package com.homeopathy.college.entity;

public enum Role {
    ROLE_GUEST,
    ROLE_STUDENT,
    ROLE_FACULTY,
    ROLE_HOD,
    ROLE_PRINCIPAL,
    ROLE_VICE_PRINCIPAL,
    ROLE_OFFICE_STAFF,
    ROLE_RECEPTION,
    ROLE_LIBRARIAN,
    ROLE_HOSPITAL_SUPERINTENDENT,
    ROLE_PHARMACIST,
    ROLE_LAB_TECHNICIAN,
    ROLE_ACCOUNTANT,
    ROLE_ADMISSION_CELL,
    ROLE_ADMIN,
    ROLE_SUPER_ADMIN
}
